In [38]:
import sys
# import hcp_utils as hcp
import sys
from scipy.io import loadmat
import numpy as np
import matplotlib
matplotlib.use('AGG')
import glob

sys.path.insert(0, '/om2/scratch/tmp/jsmentch/nat_img/code')
from matplotlib import pyplot as plt
import numpy as np

# Import the function from the file
import matplotlib.gridspec as gridspec
from PIL import Image

from analysis import plot_results
from analysis import plot_results_medial
from analysis import plot_results_medial_midthickness_alpha
from analysis import plot_results_medial_midthickness_alpha_ventralflat
from analysis import plot_results_inputalpha


In [28]:
sub='NDARHJ830RXD'
feature='cochresnet50pca1'
#feature='cochresnet50pca1hrfssfirst'
#feature='manual'
loaded=np.load(f'../pilot_results/sub-{sub}_roi-all_feat-{feature}_delay-7.npz')
#loaded=np.load(f'../good_pilots/sub-{sub}_roi-a4a5_feat-{feature}_delay-0.npz')

sub_data=loaded['stacked_r2s']


In [3]:
bootstrap_files = glob.glob(f'../pilot_results/sub-NDARHJ830RXD_roi-all_feat-cochresnet50pca1_delay-7_bootstrap-*.npz')
bootstrap_data=[]
for f in bootstrap_files:
    data=np.load(f)
    bootstrap_data.append(data['stacked_r2s'])
bootstrap_data=np.asanyarray(bootstrap_data)

p_vals=[]
for i,sub_d in enumerate(sub_data):
    bool_arr=bootstrap_data[:,i]>sub_d
    count = np.sum(bool_arr)
    p_vals.append(count/bootstrap_data.shape[0])

#bh_corrected=false_discovery_control(p_vals, method='bh')
#sub_data[bh_corrected > 0.05] = 0

In [4]:
def fdr_correction(p_values):
    # Sort the p-values in ascending order
    sorted_p_indices = np.argsort(p_values)
    sorted_p_values = np.sort(p_values)
    
    # Calculate the corrected p-values
    m = len(p_values)
    ranks = np.arange(1, m + 1)
    corrected_p_values = sorted_p_values * m / ranks
    
    # Ensure the corrected p-values are between 0 and 1
    corrected_p_values = np.minimum.accumulate(corrected_p_values[::-1])[::-1]
    
    # Return the corrected p-values in their original order
    unsorted_corrected_p_values = np.empty_like(corrected_p_values)
    unsorted_corrected_p_values[sorted_p_indices] = corrected_p_values
    
    return unsorted_corrected_p_values
bh_corrected = fdr_correction(p_vals)
#bh_corrected=false_discovery_control(p_vals, method='bh')
#sub_data[bh_corrected > 0.05] = 0

In [5]:
sub_data=np.argmax(loaded['S_average'],axis=1)
#sub_data[bh_corrected > 0.05] = -1

In [7]:
plot_results(sub_data, 's_average', '32k', None, sub, feature, 'pilot', f'DM_delay-0');
plot_results_medial(sub_data, 's_average', '32k', None, sub, feature, 'pilot', f'DM_delay-0_medial');
plot_results_medial_midthickness_alpha(sub_data, 's_average', '32k', None, sub, feature, 'pilot', f'DM_delay-0_medial_midthickness');


/om2/scratch/tmp/jsmentch/nat_img/code/nilearn_plotting_custom.py:184: MatplotlibDeprecationWarning: Axes3D(fig) adding itself to the figure is deprecated since 3.4. Pass the keyword argument auto_add_to_figure=False and use fig.add_axes(ax) to suppress this warning. The default value of auto_add_to_figure will change to False in mpl3.5 and True values will no longer work in 3.6.  This is consistent with other Axes classes.
  axes = Axes3D(figure, rect=[0, 0, 1, 1],


[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]


In [6]:
sub_data=np.argmax(loaded['S_average'],axis=1)
sub_alpha=bh_corrected
#sub_alpha[bh_corrected > 0.05] = 1
sub_alpha=1+(sub_alpha*-1)
plot_results_inputalpha(sub_data, sub_alpha, 's_average', '32k', None, sub, feature, 'pilot', f'DM_delay-7_alpha2ZZZ');


sub_data=np.argmax(loaded['S_average'],axis=1)
sub_alpha=bh_corrected
sub_alpha[bh_corrected > 0.05] = 1
sub_alpha=1+(sub_alpha*-1)
plot_results_inputalpha(sub_data, sub_alpha, 's_average', '32k', None, sub, feature, 'pilot', f'DM_delay-7_alpha1ZZZ');



/om2/scratch/tmp/jsmentch/nat_img/code/nilearn_plotting_custom.py:184: MatplotlibDeprecationWarning: Axes3D(fig) adding itself to the figure is deprecated since 3.4. Pass the keyword argument auto_add_to_figure=False and use fig.add_axes(ax) to suppress this warning. The default value of auto_add_to_figure will change to False in mpl3.5 and True values will no longer work in 3.6.  This is consistent with other Axes classes.
  axes = Axes3D(figure, rect=[0, 0, 1, 1],


[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]


## plot all of the subjects

In [ ]:
bootstrap_files = glob.glob(f'../pilot_results/sub-NDARHJ830RXD_roi-all_feat-cochresnet50pca1_delay-7_bootstrap-*.npz')
bootstrap_data=[]
for f in bootstrap_files:
    data=np.load(f)
    bootstrap_data.append(data['stacked_r2s'])
bootstrap_data=np.asanyarray(bootstrap_data)


    
    
    
with open('pilots_ru_dm_list.txt', 'r') as file:
    sub_list = file.readlines()
sub_list = [line.strip() for line in sub_list]

for sub in sub_list:
    feature='cochresnet50pca1'
    #feature='manual'
    loaded=np.load(f'../pilot_results/sub-{sub}_roi-all_feat-{feature}_delay-7.npz')
    sub_data=loaded['stacked_r2s']
    
    p_vals=[]
    for i,sub_d in enumerate(sub_data):
        bool_arr=bootstrap_data[:,i]>sub_d
        count = np.sum(bool_arr)
        p_vals.append(count/bootstrap_data.shape[0])
    bh_corrected = fdr_correction(p_vals)
    
    
    sub_data=np.argmax(loaded['S_average'],axis=1)
    sub_alpha=bh_corrected
    sub_alpha[bh_corrected > 0.05] = 1
    sub_alpha=1+(sub_alpha*-1)
    plot_results_inputalpha(sub_data, sub_alpha, 's_average', '32k', None, sub, feature, 'pilot_s', f'DM_delay-7_alpha1');
    sub_data=loaded['stacked_r2s']
    plot_results_inputalpha(sub_data, sub_alpha, 'r2', '32k', None, sub, feature, 'pilot_r2', f'DM_delay-7_alpha1');
    


## make gifs

In [12]:
#make dem gifs

from PIL import Image, ImageDraw, ImageFont
import os
import numpy as np
features=['gif']
for feature in features:
    filelist=[]
    import os
    for root, dirs, files in os.walk(f'../outputs/figures/pilot_r2'):
        for name in files:
            filelist.append(os.path.join(root, name))

    append_images=[]
    for i,f in enumerate(filelist):
        if i==0:
            img1 = Image.open(f)
        else:
            img2 = Image.open(f)
            append_images.append(img2)
    img1.save(f'../plots/pilots_r2_rough.gif', save_all=True, append_images=append_images, duration=100, loop=0)

In [13]:
#make dem gifs

from PIL import Image, ImageDraw, ImageFont
import os
import numpy as np
features=['gif']
for feature in features:
    filelist=[]
    import os
    for root, dirs, files in os.walk(f'../outputs/figures/pilot_s'):
        for name in files:
            filelist.append(os.path.join(root, name))

    append_images=[]
    for i,f in enumerate(filelist):
        if i==0:
            img1 = Image.open(f)
        else:
            img2 = Image.open(f)
            append_images.append(img2)
    img1.save(f'../plots/pilots_s_rough.gif', save_all=True, append_images=append_images, duration=100, loop=0)

## plot selected ROIs

In [30]:

sub='NDARHJ830RXD'
feature='cochresnet50pca1'
#feature='cochresnet50pca1hrfssfirst'
#feature='manual'
loaded=np.load(f'../good_pilots/sub-02_roi-a4a5_feat-cochresnet50srp05hrffriends_s01e02b_delay-0_friends_yz.npz')
#loaded=np.load(f'../good_pilots/sub-{sub}_roi-a4a5_feat-{feature}_delay-0.npz')

sub_data=loaded['stacked_r2s']


In [31]:
def load_glasser():
    atlas_dlabel='/om2/user/jsmentch/atlases/atlas-Glasser/atlas-Glasser_space-fsLR_den-91k_dseg.dlabel.nii'
    img = nb.load(atlas_dlabel)
    atlas_data=img.get_fdata()
    atlas_data=atlas_data[0,:]
    atlas=pd.read_csv('/om2/user/jsmentch/atlases/atlas-Glasser/atlas-Glasser_dseg.tsv', sep='\t')
    return(atlas,atlas_data)

def get_parcel_indices(atlas, parcels):
    #parcels MUST be a list of strings
    patternR = '|'.join(['Right_' + parcel for parcel in parcels])
    patternL = '|'.join(['Left_' + parcel for parcel in parcels])
    
    # get a boolean series where True indicates a match
    matches = atlas['label'].str.contains(patternR) | atlas['label'].str.contains(patternL)
    
    # get the indices that match
    atlas_indices = atlas[matches]['index'].tolist()
    indices = matches[matches].index.tolist()
    parcel_names=atlas[matches]['label'].tolist()
    return(atlas_indices,indices,parcel_names)

def extract_parcels(parcels):
    atlas,atlas_data=load_glasser()
    atlas_indices,indices,parcel_names=get_parcel_indices(atlas,parcels)
    atlas_indices_indices = np.where(np.isin(atlas_data, atlas_indices))[0]
    print(f'loaded parcels {parcels}')
    return(atlas_indices_indices)

def select_parcels(parcel_selection):
    #parcels: auditory, visual, audiovideo, all, custom
    if parcel_selection == 'auditory':
        parcels=[
        'A1',
        'LBelt',
        'MBelt',
        'PBelt',
        'A4',
        'TA2',
        'A5']
    elif parcel_selection == 'a4a5':
        parcels=[
        'A4',
        'A5']
    elif parcel_selection == 'visual':
        parcels=[
                'V1',
                'V2',
                'V3',
                'V4',
                'MT',
                'MST',
                'V4t',
                'FST',
                'FFC',
                'V8',
                'PIT',
                'VVC',
                'VMV1',
                'VMV2',
                'VMV3',
                'V3A',
                'V3B',
                'V6',
                'V6A',
                'V7']
    elif parcel_selection == 'earlyvisual':
        parcels=[
                'V1',
                'V2',
                'V3',
                'V4',
                'MT']

    elif parcel_selection == 'ventralvisual':
        parcels=[
                'FFC',
                'V8',
                'PIT',
                'VVC',
                'VMV1',
                'VMV2',
                'VMV3']
    elif parcel_selection == 'audiovisual':
        parcels=[
                'IPS1',
                'IFSa',
                'IFSp',
                'IFJa',
                'IFJp',
                'FEF',
                'STSvp',
                'STSdp',
                'STSva',
                'STSda',
                'STGa',
                'STV',
                'TPOJ1',
                'TPOJ2',
                'TPOJ3']
    elif parcel_selection == 'all_select':
        parcels=[
                'V1',
                'V2',
                'V3',
                'V4',
                'MT',
                'MST',
                'V4t',
                'FST',
                'FFC',
                'V8',
                'PIT',
                'VVC',
                'VMV1',
                'VMV2',
                'VMV3',
                'V3A',
                'V3B',
                'V6',
                'V6A',
                'V7',
                'IPS1',
                'IFSa',
                'IFSp',
                'IFJa',
                'IFJp',
                'FEF',
                'STSvp',
                'STSdp',
                'STSva',
                'STSda',
                'STGa',
                'STV',
                'TPOJ1',
                'TPOJ2',
                'TPOJ3',
                'A1',
                'LBelt',
                'MBelt',
                'PBelt',
                'A4',
                'TA2',
                'A5']
    return(parcels)

In [39]:
import nibabel as nb
import pandas as pd
import numpy as np

parcels=select_parcels('auditory') # load parcel set
atlas_indices_indices=extract_parcels(parcels) # get indices of parcels

loaded parcels ['A1', 'LBelt', 'MBelt', 'PBelt', 'A4', 'TA2', 'A5']


In [33]:
scores=np.zeros((91282,))
scores[atlas_indices_indices]=sub_data

In [ ]:
plot_results(scores, 'r2', '32k', None, '02', 'cochresnet50srp05hrffriends', 'pilot', f's01e02b_delay-0');


In [ ]:
for sub in ['01','02','03','04','05','06']:
    loaded=np.load(f'../good_pilots/sub-{sub}_roi-auditory_feat-cochresnet50pca10hrffriends_s01e02b_delay-0_friends.npz')
#loaded=np.load(f'../good_pilots/sub-{sub}_roi-a4a5_feat-{feature}_delay-0.npz')

    sub_data=loaded['stacked_r2s']
    scores=np.zeros((91282,))
    scores[atlas_indices_indices]=sub_data
    plot_results(scores, 'r2', '32k', None, sub, 'cochresnet50pca10hrffriends', 'pilot', f's01e02b_delay-0');


In [41]:
for sub in ['01','02','03','04','05','06']:
    loaded=np.load(f'../good_pilots/sub-{sub}_roi-auditory_feat-cochresnet50pca10hrffriends_s01e02b_delay-0_friends.npz')
#loaded=np.load(f'../good_pilots/sub-{sub}_roi-a4a5_feat-{feature}_delay-0.npz')

    sub_data=np.argmax(loaded['S_average'],axis=1)
    scores=np.zeros((91282,))
    scores[atlas_indices_indices]=sub_data
    plot_results(scores, 's_average', '32k', None, sub, 'cochresnet50pca10hrffriends', 'pilot', f's01e02b_delay-0');


/om2/scratch/tmp/jsmentch/nat_img/code/nilearn_plotting_custom.py:184: MatplotlibDeprecationWarning: Axes3D(fig) adding itself to the figure is deprecated since 3.4. Pass the keyword argument auto_add_to_figure=False and use fig.add_axes(ax) to suppress this warning. The default value of auto_add_to_figure will change to False in mpl3.5 and True values will no longer work in 3.6.  This is consistent with other Axes classes.
  axes = Axes3D(figure, rect=[0, 0, 1, 1],


[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875]
[0.    0.125

In [ ]:
# calculate noise ceiling for a ROI / subject
# run encoding model on ROI
# plot weights for ROI