In [1]:
import sys
# import hcp_utils as hcp
import sys
from scipy.io import loadmat
import numpy as np
import matplotlib
matplotlib.use('AGG')
import glob

sys.path.insert(0, '/om2/scratch/tmp/jsmentch/nat_img/code')
from matplotlib import pyplot as plt
import numpy as np

# Import the function from the file
import matplotlib.gridspec as gridspec
from PIL import Image

from analysis import plot_results
from analysis import plot_results_medial
from analysis import plot_results_medial_midthickness_alpha
from analysis import plot_results_medial_midthickness_alpha_ventralflat
from analysis import plot_results_inputalpha


/opt/miniconda-latest/lib/python3.8/site-packages/nilearn/datasets/__init__.py:87: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
pixdim[1,2,3] should be non-zero; setting 0 dims to 1
/om2/scratch/tmp/jsmentch/nat_img/code/analysis.py:27: MatplotlibDeprecationWarning: You are modifying the state of a globally registered colormap. This has been deprecated since 3.3 and in 3.6, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = mpl.cm.get_cmap("RdBu").copy()
  cmap.set_bad(color='gray')


In [2]:
sub='NDARHJ830RXD'
feature='cochresnet50pca1'
#feature='manual'
loaded=np.load(f'../pilot_results/sub-{sub}_roi-all_feat-{feature}_delay-7.npz')
sub_data=loaded['stacked_r2s']


In [3]:
bootstrap_files = glob.glob(f'../pilot_results/sub-NDARHJ830RXD_roi-all_feat-cochresnet50pca1_delay-7_bootstrap-*.npz')
bootstrap_data=[]
for f in bootstrap_files:
    data=np.load(f)
    bootstrap_data.append(data['stacked_r2s'])
bootstrap_data=np.asanyarray(bootstrap_data)

p_vals=[]
for i,sub_d in enumerate(sub_data):
    bool_arr=bootstrap_data[:,i]>sub_d
    count = np.sum(bool_arr)
    p_vals.append(count/bootstrap_data.shape[0])

#bh_corrected=false_discovery_control(p_vals, method='bh')
#sub_data[bh_corrected > 0.05] = 0

In [4]:

def fdr_correction(p_values):
    # Sort the p-values in ascending order
    sorted_p_indices = np.argsort(p_values)
    sorted_p_values = np.sort(p_values)
    
    # Calculate the corrected p-values
    m = len(p_values)
    ranks = np.arange(1, m + 1)
    corrected_p_values = sorted_p_values * m / ranks
    
    # Ensure the corrected p-values are between 0 and 1
    corrected_p_values = np.minimum.accumulate(corrected_p_values[::-1])[::-1]
    
    # Return the corrected p-values in their original order
    unsorted_corrected_p_values = np.empty_like(corrected_p_values)
    unsorted_corrected_p_values[sorted_p_indices] = corrected_p_values
    
    return unsorted_corrected_p_values
bh_corrected = fdr_correction(p_vals)
#bh_corrected=false_discovery_control(p_vals, method='bh')
#sub_data[bh_corrected > 0.05] = 0

In [5]:
sub_data=np.argmax(loaded['S_average'],axis=1)
#sub_data[bh_corrected > 0.05] = -1

In [18]:
plot_results(sub_data, 's_average', '32k', None, sub, feature, 'pilot', f'DM_delay-7');
plot_results_medial(sub_data, 's_average', '32k', None, sub, feature, 'pilot', f'DM_delay-7_medial');
plot_results_medial_midthickness_alpha(sub_data, 's_average', '32k', None, sub, feature, 'pilot', f'DM_delay-7_medial_midthickness');


[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]


In [7]:
sub_data=np.argmax(loaded['S_average'],axis=1)
sub_alpha=bh_corrected
#sub_alpha[bh_corrected > 0.05] = 1
sub_alpha=1+(sub_alpha*-1)
plot_results_inputalpha(sub_data, sub_alpha, 's_average', '32k', None, sub, feature, 'pilot', f'DM_delay-7_alpha2');


sub_data=np.argmax(loaded['S_average'],axis=1)
sub_alpha=bh_corrected
sub_alpha[bh_corrected > 0.05] = 1
sub_alpha=1+(sub_alpha*-1)
plot_results_inputalpha(sub_data, sub_alpha, 's_average', '32k', None, sub, feature, 'pilot', f'DM_delay-7_alpha1');



/om2/scratch/tmp/jsmentch/nat_img/code/nilearn_plotting_custom.py:184: MatplotlibDeprecationWarning: Axes3D(fig) adding itself to the figure is deprecated since 3.4. Pass the keyword argument auto_add_to_figure=False and use fig.add_axes(ax) to suppress this warning. The default value of auto_add_to_figure will change to False in mpl3.5 and True values will no longer work in 3.6.  This is consistent with other Axes classes.
  axes = Axes3D(figure, rect=[0, 0, 1, 1],


[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]
[0.    0.125 0.25  0.375 0.5   0.625]


## plot all of the subjects

In [ ]:
bootstrap_files = glob.glob(f'../pilot_results/sub-NDARHJ830RXD_roi-all_feat-cochresnet50pca1_delay-7_bootstrap-*.npz')
bootstrap_data=[]
for f in bootstrap_files:
    data=np.load(f)
    bootstrap_data.append(data['stacked_r2s'])
bootstrap_data=np.asanyarray(bootstrap_data)


    
    
    
with open('pilots_ru_dm_list.txt', 'r') as file:
    sub_list = file.readlines()
sub_list = [line.strip() for line in sub_list]

for sub in sub_list:
    feature='cochresnet50pca1'
    #feature='manual'
    loaded=np.load(f'../pilot_results/sub-{sub}_roi-all_feat-{feature}_delay-7.npz')
    sub_data=loaded['stacked_r2s']
    
    p_vals=[]
    for i,sub_d in enumerate(sub_data):
        bool_arr=bootstrap_data[:,i]>sub_d
        count = np.sum(bool_arr)
        p_vals.append(count/bootstrap_data.shape[0])
    bh_corrected = fdr_correction(p_vals)
    
    
    sub_data=np.argmax(loaded['S_average'],axis=1)
    sub_alpha=bh_corrected
    sub_alpha[bh_corrected > 0.05] = 1
    sub_alpha=1+(sub_alpha*-1)
    plot_results_inputalpha(sub_data, sub_alpha, 's_average', '32k', None, sub, feature, 'pilot_s', f'DM_delay-7_alpha1');
    sub_data=loaded['stacked_r2s']
    plot_results_inputalpha(sub_data, sub_alpha, 'r2', '32k', None, sub, feature, 'pilot_r2', f'DM_delay-7_alpha1');
    


In [12]:
#make dem gifs

from PIL import Image, ImageDraw, ImageFont
import os
import numpy as np
features=['gif']
for feature in features:
    filelist=[]
    import os
    for root, dirs, files in os.walk(f'../outputs/figures/pilot_r2'):
        for name in files:
            filelist.append(os.path.join(root, name))

    append_images=[]
    for i,f in enumerate(filelist):
        if i==0:
            img1 = Image.open(f)
        else:
            img2 = Image.open(f)
            append_images.append(img2)
    img1.save(f'../plots/pilots_r2_rough.gif', save_all=True, append_images=append_images, duration=100, loop=0)

In [13]:
#make dem gifs

from PIL import Image, ImageDraw, ImageFont
import os
import numpy as np
features=['gif']
for feature in features:
    filelist=[]
    import os
    for root, dirs, files in os.walk(f'../outputs/figures/pilot_s'):
        for name in files:
            filelist.append(os.path.join(root, name))

    append_images=[]
    for i,f in enumerate(filelist):
        if i==0:
            img1 = Image.open(f)
        else:
            img2 = Image.open(f)
            append_images.append(img2)
    img1.save(f'../plots/pilots_s_rough.gif', save_all=True, append_images=append_images, duration=100, loop=0)